admin/admin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from administrer import views
import authentication.views





urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include(('administrer.urls', 'adminstrer'), namespace='administrer')),
    path('index/', views.index, name='index'),
    path('inbox/notifications/',include(('notifications.urls', 'notifications'), namespace='notifications')),

    
    
    path('', authentication.views.login_page, name='login'),
    path('logout/', authentication.views.logout_user, name='logout'),
    path('signup/', authentication.views.signup_page, name='signup'),


    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin/administrer/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns =[

    path('index/', views.index, name='index'),
    path('statistique/', views.dashboard, name='dashboard'),

    path('add/personne', views.personne, name='person_add'),
    path('ajax/load-cities/', views.load_cities,name='ajax_load_cities'),  
    path('liste/personne', views.listePerson, name='person_changelist'),
    path('search/', views.search,name='search'),
    path('<int:id>/', views.ModiPers, name='person_change'),
    path('Supprimer/<int:id>', views.supPerson, name='supPerson'),
    path('details/<pk>', views.detail, name='details'),
    path('add/courrier', views.AddCour, name='AddCour'),
    path('liste/courrier', views.liste, name='liste'),
    path('modifier/courrier/<int:id>', views.Modif, name='Modif'),
    path('supprimer/courrier/<int:id>', views.suppression, name='suppression'),
    path('pdf/courrier/<pk>', views.pdf, name='pdf'),
    # path('statistique/courrier', views.listeDirec, name='listeDirec'),
    path('statistique/personnel', views.dash, name='dash'),














]
if settings.DEBUG:  # add this
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

admin/administrer/forms.py
from django import forms
from .models import *
from django.forms import ModelForm


class XYZ_DateInput(forms.DateInput):
    input_type = "date"

    def __init__(self, **kwargs):
        kwargs["format"] = "%Y-%m-%d"
        # kwargs["format"] = "%d-%m-%Y"
        super().__init__(**kwargs)


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = "__all__"

        widgets = {
            'datePrise': XYZ_DateInput(format=["%Y-%m-%d"],),
            'dateEnr': XYZ_DateInput(format=["%Y-%m-%d"],),
            'dateE': XYZ_DateInput(format=["%Y-%m-%d"],),

            'dteNaiss_per': XYZ_DateInput(format=["%Y-%m-%d"],),
            'nom_per':forms.TextInput(attrs={'required': True}),

        }
      

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['service'].queryset = Service.objects.none()

        if 'sousdirection' in self.data:
            try:
                sousdirection_id = int(self.data.get('sousdirection'))
                self.fields['service'].queryset = Service.objects.filter(
                    sousdirection_id=sousdirection_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['service'].queryset = self.instance.sousdirection.service_set.order_by('name')


    
class EntiteForm(ModelForm):
    class Meta:
        model = Entite
        fields = "__all__"




class CourrierForm(ModelForm):
    class Meta:
        model = Courrier
        fields = "__all__"
        widgets = {
            'DestRecp': forms.Select(attrs={'class': 'form-control'}),
            'num_AccRecp_cour': forms.NumberInput(attrs={'class': 'form-control'}),
            'type_cour': forms.TextInput(attrs={'class': 'form-control'}),
            'obj_cour': forms.Textarea(attrs={'class': 'form-control',"rows":3, "cols":10}),
            'num_ordre_cour': forms.NumberInput(attrs={'class': 'form-control'}),
            'type_cour': forms.Select(attrs={'class': 'form-control','type': 'select'}),
            
            'date_Emiss_cour':XYZ_DateInput(format=["%Y-%m-%d"],),
            'date_AccuseRecp_cour': XYZ_DateInput(format=["%Y-%m-%d"],),
            
        }
   

admin/administrer/views.py
from http.client import HTTPResponse
from django.http import HttpResponseNotFound,HttpResponse
from urllib import response
from django.shortcuts import render,get_object_or_404,redirect
from requests import delete
from .models import *
from authentication.models import *

from .forms import *
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
import os
from django.db.models import Count
from notifications.signals import notify
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.conf import settings
from django.contrib.staticfiles import finders
from django.contrib.auth.decorators import login_required,permission_required

@login_required
def index(request):
    return render(request,"index.html")


def search(request):
   person = Person.objects.order_by('dateEnr').reverse()
   query = request.GET.get('query')
   if query != '' and query is not None:
       person = Person.objects.filter(Q(nom_per__icontains=query) | Q(pren_per__icontains=query) | Q(
           lieu__icontains=query) | Q(Mat_per__icontains=query) | Q(Meca_per__icontains=query) | Q(Type_per__icontains=query))
   paginator = Paginator(person, 10)
   page = request.GET.get('page')
   page_obj = paginator.get_page(page)
   context = {
       'person': person,
       'page_obj': page_obj
   }
   return render(request, 'personnel/liste_per.html', context)

    


def load_cities(request):
    sousdirection_id = request.GET.get('sousdirection')
    services = Service.objects.filter(
        sousdirection_id=sousdirection_id).order_by('name')
    return render(request, 'personnel/liste.html', {'services': services})


@login_required
@permission_required('administrer.add_person')
def personne(request):
    user = User.objects.get(role="PERSONNEL")
    users = User.objects.get(role="ADMINISTRATION")
    if request.method == 'POST':
        form=PersonForm(request.POST,request.FILES)
        if form.is_valid():
           form.save()
           form = PersonForm()
           messages.success(request, 'les données ont été enregistré.')
           notify.send(user,recipient=users,verb='a enregistré une fiche personnel',target=users)
    else:
        form=PersonForm()
    return render(request, 'personnel/person_form.html',{'form': form})


@login_required
@permission_required('administrer.view_person')
def listePerson(request):
   person = Person.objects.order_by('dateEnr').reverse()
   query = request.GET.get('query')
   if query != '' and query is not None:
       person = Person.objects.filter(Q(nom_per__icontains=query) | Q(pren_per__icontains=query) | Q(
           lieu__icontains=query) | Q(Mat_per__icontains=query) | Q(Meca_per__icontains=query) | Q(Type_per__icontains=query))
   paginator = Paginator(person, 7)
   page = request.GET.get('page')
   page_obj = paginator.get_page(page)
   context = {
       'person': person,
       'page_obj': page_obj

   }
   return render(request, 'personnel/liste_per.html', context)


@login_required
@permission_required('administrer.change_person')
def ModiPers(request, id):
    personne = get_object_or_404(Person, id=id)
    if request.method == 'POST':
        form = PersonForm(request.POST, request.FILES, instance=personne)
        if form.is_valid():
           form.save()
           form = PersonForm(instance=personne)
           messages.success(request, 'les données ont été enregistré.')
    else:
        form = PersonForm(instance=personne)
    return render(request, 'Personnel/edit_per.html', {'form': form})




def supPerson(request, id):
    person = get_object_or_404(Person, id=id)
    if request.method == 'POST':
        person.delete()
        messages.success(request, 'le courrier a été supprimé avec success.')
    return redirect('/liste/personne')


def link_callback(uri, rel):
    """
    Convert HTML URIs to absolute system paths so xhtml2pdf can access those
    resources
    """
    result = finders.find(uri)
    if result:
        if not isinstance(result, (list, tuple)):
            result = [result]
        result = list(os.path.realpath(path) for path in result)
        path = result[0]
    else:
        sUrl = settings.STATIC_URL        # Typically /static/
        sRoot = settings.STATIC_ROOT      # Typically /home/userX/project_static/
        mUrl = settings.MEDIA_URL         # Typically /media/
        mRoot = settings.MEDIA_ROOT       # Typically /home/userX/project_static/media/

        if uri.startswith(mUrl):
            path = os.path.join(mRoot, uri.replace(mUrl, ""))
        elif uri.startswith(sUrl):
            path = os.path.join(sRoot, uri.replace(sUrl, ""))
        else:
            return uri

    # make sure that file exists
    if not os.path.isfile(path):
        raise Exception(
            'media URI must start with %s or %s' % (sUrl, mUrl)
        )
    return path






def detail(request, *args, **kwargs):
    pk = kwargs.get('pk')
    person = get_object_or_404(Person, pk=pk)
    template_path = 'personnel/pdf.html'
    #pour charger image
    BASE_URL = request.scheme+'://'+request.get_host()
    context = {'person': person, 'base_url': BASE_URL}

    #return HttpResponse(request.scheme+'://'+request.get_host())
   # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
   # to directly download the pdf we need attachment
   # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
   # to view on browser we catDG?n remove attachment
    response['Content-Disposition'] = 'filename="report.pdf"'
   # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)
   # create a pdf
    pisa_status = pisa.CreatePDF(
        html, dest=response, link_callback=link_callback)

   # if error then show some funy view
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response


# def mark_all_as_read(request):
#     request.user.notifications.mark_all_as_read()

#     _next = request.GET.get('next')

#     if _next:
#         return redirect(_next)
#     return redirect('notifications:unread')

@login_required
@permission_required(['administrer.add_courrier','administrer.add_entite'])
def AddCour(request):
    ent = EntiteForm()
    form = CourrierForm()
    if request.method == 'POST':
        form = CourrierForm(request.POST,request.FILES)
        if form.is_valid():
                form.save()
                form = CourrierForm()
                messages.success(request, 'le courrier a été enregistré!!.')
                # notify.send(users, recipient=user, verb='a enregistré un courrier')
        ent = EntiteForm(request.POST)
        if ent.is_valid():
                ent.save()
                ent = EntiteForm()
                messages.success(request, 'la personne a été enregistré!!.')

    context = {
        'form':form,
        'ent': ent,
    }
    return render(request, 'courrier/ajout.html', context=context)


@login_required
@permission_required('administrer.view_courrier')
def liste(request):
    liste = Courrier.objects.order_by('date_ajout').reverse()
   # return HttpResponse(liste.exists())
    query=request.GET.get('query')
    if query != '' and query is not None:
         liste = Courrier.objects.filter(Q(num_ordre_cour__icontains=query) | Q(obj_cour__icontains=query) | Q(type_cour__icontains=query))
    paginator = Paginator(liste,6)
    page= request.GET.get('page')
    liste=paginator.get_page(page)
    context = {
        'liste': liste,
    }
    return render(request, 'courrier/liste.html', context)



@login_required
@permission_required(['administrer.change_courrier','administrer.change_entite'])
def Modif(request,id):
    ent = EntiteForm()
    courrier= get_object_or_404(Courrier,id=id)
    form = CourrierForm(instance=courrier)
    if request.method == 'POST':
        form = CourrierForm(request.POST,request.FILES,instance=courrier)
        if form.is_valid():
                form.save()
                form = CourrierForm(instance=courrier)
                messages.success(request, 'le courrier a été enregistré!!.')
        ent = EntiteForm(request.POST)
        if ent.is_valid():
                ent.save()
                ent = EntiteForm()
                messages.success(request, 'la personne a été enregistré!!.')

    context = {
            'form':form,
            'ent': ent,
    }
    return render(request, 'courrier/edit.html', context=context)



def suppression(request,id):
    courrier= get_object_or_404(Courrier,id=id)
    if request.method == 'POST':
        courrier.delete()
        messages.success(request, 'le courrier a été supprimé avec success.')
    return redirect('/liste/courrier')






def pdf(request, *args, **kwargs):
    pk = kwargs.get('pk')
    courrier = get_object_or_404(Courrier, pk=pk)
    template_path = 'courrier/details.html'
    context = {'courrier': courrier}
   # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
   # to directly download the pdf we need attachment
   # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
   # to view on browser we catDG?n remove attachment
    response['Content-Disposition'] = 'filename="report.pdf"'
   # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)
   # create a pdf
    pisa_status = pisa.CreatePDF(
        html, dest=response, link_callback=link_callback)
   # if error then show some funy view
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response





    
def listeDirec(request):
    liste = Courrier.objects.order_by('date_ajout').filter(type_cour='ENTRANT').reverse() 
   # return HttpResponse(liste.exists())
    query=request.GET.get('query')

admin/administrer/templates/courrier/ajout.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
  
<br/>
<br/>
<br/>
<br/>

	
    <div class="section-body">
      <div class="row">
        <div class="col-12 col-md-6 col-lg-12">
          <div class="card border b+">

            <form method="POST" enctype="multipart/form-data"> 
                                       {% csrf_token %}

              <div class="card-header">
                  
                <CENTER><h4> <i class="fa fa-align-center  icon-envelope-letter" aria-hidden="true">FORMULAIRE</i></h4></CENTER>

              </div>
              <div class="card-body">
                <div class="row mbs-4">
                  <div class="col">
                    <div class="form-outline">
                         <label class="form-label" for="form6Example2"
                        >Destinataire/Recepteur:</label>

                      <div class="input-group mb-3 w-100 mt-2 p-2">
                        {{ form.DestRecp}}
                                    

                          <!-- Button trigger modal -->
                          <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo"><i class="fa fa-plus"></i></button>
                  </div>

                    </div>
                  </div>
                  <div class="col">
                    
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <div class="form-outline">
                      <label class="form-label" for="form6Example2"
                        >Numero Accusé de reception:</label
                      >

                      {{ form.num_AccRecp_cour|add_class:'form-control'}}


                    </div>
                  </div>
                </div>

                <div class="row mb-4">
                    <div class="col">
                      <div class="form-outline">
                        <label class="form-label" for="form6Example1"
                          >Date d'emission:</label
                        >
                        {% render_field form.date_Emiss_cour|add_class:"form-control" type="date" placeholder="select" %}
  
                      </div>
                    </div>
                    <div class="col">
                      <div class="form-outline">
                        <label class="form-label" for="form6Example2"
                          >Date Accussé de reception:</label
                        >
                        {% render_field form.date_AccuseRecp_cour|add_class:"form-control" type="date" placeholder="select" %}
  
                      </div>
                    </div>
                  </div>

                <div class="row mb-4">
                  <div class="col">
                    <div class="form-outline">
                      <label class="form-label" for="form6Example1"
                        >Type de Courrier:</label
                      >
                      {{form.type_cour}}
                    </div>
                  </div>
                  <div class="col">
                    <div class="form-outline">

            <label class="form-label" for="form6Example1" 
                        >Numero d'ordre:</label
                      >

                      {{ form.num_ordre_cour }}


                   
                    </div>
                  </div>
                </div>

                <div class="row mb-4">
                  <div class="col">
                    <div class="form-outline">
                      <label class="form-label" for="form6Example1"
                        >Objet:</label
                      >
                      {{ form.obj_cour}}
                    </div>
                  </div>
                  <div class="col">
                    
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <div class="form-outline">
                      <label class="form-label" for="form6Example2"
                        >Fichier</label
                      >
                      {% render_field form.file_cour|add_class:"form-control" type="file" %}

                   
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-footer text-center">
                  <button type="submit" class="btn btn-primary">
                    <i class="fa fa-magic"></i>&nbsp; Valider
                  </button>
             
              </div>
            </form>

	<!--start overlay-->
		  <div class="overlay toggle-menu"></div>
		<!--end overlay-->

    </div>
    <!-- End container-fluid-->

    
    {% include "courrier/entite.html" %}


   </div><!--End content-wrapper-->
   <!--Start Back To Top Button-->
    <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
    <!--End Back To Top Button-->
	
	<!--Start footer-->
	
  <!--end color switcher-->
   

 
  




{% endblock content %}

admin/administrer/templates/courrier/chart.html
{% block content %}
  <div id="container" style="width: 90%;">
    <canvas id="pie-chart"></canvas>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    var config = {
      type: 'doughnut',
      data: {
        datasets: [{
          labels: ('Entité(s)'),

          data: {{ series|safe }},
          backgroundColor: [
            '#0083ff', '#ffff6b', '#8b008b', '#ff0921', '#D3D3D3'
          ],
          labels: 'Entité(s)'
        }],
        labels: {{ labelo|safe }}

      },
      options: {
        responsive: true
      }
    };

    window.onload = function() {
      var ctx = document.getElementById('pie-chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };

  </script>

{% endblock %}

admin/administrer/templates/courrier/dashboard.html
{% extends "base.html" %}

{% block content %}


  <!--Start Dashboard Content-->

	<div class="card mt-3">
   {% include "courrier/entetes.html" %}
 </div>  
	  
	
	<div class="row">
     <div class="col-12 col-lg-8 col-xl-8">
	    <div class="card ">
		 <div class="card-header">Courriers/ans
		   <div class="card-action">
			 <div class="dropdown">
			 
				
			  </div>
		   </div>
		 </div>
		 <div class="card-body">
		   
			<div class="chart-container-1">
        {% include "courrier/statistique.html" %}
			  <canvas id="chart1">        
</canvas>

			</div>
		 </div>
		 
		 <div class="row m-0 row-group text-center border-top border-light-3">
		   
		   <div class="col-12 col-lg-4">
		     <div class="p-3">
		     </div>
		   </div>
		 </div>
		 
		</div>
	 </div>
     <div class="col-12 col-lg-4 col-xl-4">
        <div class="card">
           <div class="card-header">Total Entité(s)/ans
             <div class="card-action">
             <div class="dropdown">
           
             
              </div>
             </div>
           </div>
           <div class="card-body">
		     <div class="chart-container-2">
          {% include "courrier/chart.html" %}
               <canvas id="chart2"></canvas>
			  </div>
           </div>
           <div class="table-responsive">
             <table class="table align-items-center">
               <tbody>
               </br>
                 <tr>
                   <td><i class="fa fa-circle text-white mr-2"></i>Nombre Total d'entités par/ans</td>
                    <td>Total</td>
                


               </tbody>
             </table>
           </div>
         </div>
     </div>
	</div><!--End Row-->



  <div class="row">
	 <div class="col-12 col-lg-12">
	   <div class="card ">
	     <div class="card-header">Tableaux des enregistrements récents
		  <div class="card-action">
             <div class="dropdown">
           
            
              </div>
             </div>
		 </div>
	       <div class="table-responsive">
                 <table class="table align-items-center table-flush table-borderless">
                  <thead>
                   <tr>
                     <th>N'D'ORDRE</th>
                     <th>Fichier</th>
                     <th>Date accusé</th>
                     <th>Objet</th>
                     <th>Type</th>
                     <th>DEST/RECP</th>
                   </tr>
                   </thead>
                   <tbody><tr>
                  {% for cour in courrier %}
                   <td>{{cour.num_ordre_cour}}</td>
                       <td><a href="/media/{{cour.file_cour}}"><img src="https://via.placeholder.com/110x110" class="product-img" alt="product img"> 
                  </a></td>
                  <td>
                    <div>{{cour.date_AccuseRecp_cour}}</div>
                  </td>
                  <td>{{cour.obj_cour}}</td>
                  <td>
                    <div  class=" {% if cour.type_cour == "TRANSMISSION" %}badge badge-warning{% elif cour.type_cour == 'INTERNE' %}badge badge-primary{% elif cour.type_cour == 'ENTRANT' %}badge badge-success{% else %}badge badge-danger{% endif %}">{{ cour.type_cour }}</div>




                  </td>
                  <td>{{cour.DestRecp}}</td>
                 
                
                </tr>
              {% endfor %}


                 </tbody></table>
               </div>
	   </div>
	 </div>
	</div><!--End Row-->

      <!--End Dashboard Content-->
	  
	<!--start overlay-->
		  <div class="overlay toggle-menu"></div>
		<!--end overlay-->
		
    </div>
    <!-- End container-fluid-->
    
    </div><!--End content-wrapper-->
   <!--Start Back To Top Button-->
    <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
    <!--End Back To Top Button-->
	

  
{% endblock content %}

admin/administrer/templates/courrier/liste.html
{% extends 'base.html' %}
{% load static %}




{% block content %}
 

 
<div class="clearfix"></div>

  <!--Start Dashboard Content-->

</br>
</br>
</br>


	
<div class="container">
  <form  method="get">
    <fieldset>    
      <div class="input-group">
        <input name="query" type="search" class="form-control" aria-label="Saisie de mots clés" placeholder="En fonction de l'objet , du numero d'ordre ou du type " required="required">
        <div class="input-group-append">
          <button class="btn btn-primary" type="submit">Recherche</button>
        </div>
      </div>
    </fieldset> 
  </form>

{% if liste|length_is:"0" %}
</br>
</br>
  <div class="text-center text-danger"> <p>Nous n'avons pas trouvé de requêtes!!!</div>

{% else %}

  </div>

  </br>
  </br>
  </br>
	<div class="row">
	 <div class="col-12 col-lg-12">
	   <div class="card">
	     <div class="card-header"><a href="{% url 'administrer:AddCour' %}" class="btn btn-icon btn-primary" ><i class="fa fa-plus"></i></a>

	       <div class="table-responsive">
                 <table class="table align-items-center  table table-hover table-flush table-borderless">
                  <thead>
                   <tr>
                <th scope="col"> Date Enregistrement</th>
                <th scope="col"> N°d'ordre</th>
                <th scope="col">Type Courrier</th>
                <th scope="col">Objet</th>
                <th scope="col">Fichier</th>
                <th scope="col">Entite</th>
                <th scope="col">Date d'emission</th>
                <th scope="col">Date d'accusé de reception</th> 
                <th scope="col">Operations</th>
                   </tr>
                   </thead>
                   <tbody>
                    {% for liste in liste  %}

                  <tr>
                    <td>{{ liste.date_ajout}}</td>

                    <td>{{ liste.num_ordre_cour }}</td>
                    <td   style="font-weight: bold"  class="container mt-1 fst-italic {% if liste.type_cour == "TRANSMISSION" %}badge rounded-pill bg-secondary{% elif liste.type_cour == 'INTERNE' %}badge rounded-pill bg-primary{% elif liste.type_cour == 'ENTRANT' %}badge rounded-pill bg-success{% else %}badge rounded-pill bg-warning{% endif %}">{{ liste.type_cour }}</td>
                    <td>{{ liste.obj_cour }}</td>
                    <td><a href="/media/{{liste.file_cour}}"><img src="https://via.placeholder.com/110x110" class="product-img" alt="product img"> </a> </td>
                    <td>{{ liste.DestRecp  }}</td>

                    
                    <td>{{ liste.date_Emiss_cour  }}</td>
                    <td>{{ liste.date_AccuseRecp_cour}}</td>
                    <td>{{ liste.date_ajout }}</td>
                    <td>

                      <a href="{% url 'administrer:Modif' liste.id %}" class="btn btn-icon btn-primary"><i class="fa fa-pencil"></i></a>


                      <a href="{% url 'administrer:pdf' liste.id %}" class="btn btn-icon btn-warning"><i class="fa fa-eye"></i></a>

                <a
                href="{% url 'administrer:suppression' liste.id %}"
                class="btn btn-icon btn-danger "
                data-toggle="modal"
                data-target="#delete-item-modal"
                onclick="delete_user(this)">

                <i class="fa fa-trash"></i>

                </a>


              <div class="modal fade" id="delete-item-modal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                          <p class="text-danger fw-bold">êtes-vous sûr de vouloir supprimer???</p>
                        </div>
                        <div class="justify-content-between mb-2 mr-2 text-right">
                            <form method="post"
                                  id="item-delete-form"
                            >
                                <button type="button" class="btn btn-secondary mr-1" data-dismiss="modal">Annuler</button>
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger" id="confirm-delete-item-button">Supprimer</button>
                            </form>
                        </div>
                     </div>
                    </div>
                  </div>


                    </td>
                    
                   </tr>

                   

				

                 </tbody>
                 {% endfor %}
{% endif %}
                
                </table>
               </div>
	   </div>

     <div class="row mt-3">
      <div class="col-md-3 offset-md-4">

              <ul class="pagination">

                  {% if liste.has_previous %}
                  
                      
                <li class="page-item ">
                  <a class="page-link" href="?page= {{ liste.previous_page_number }}" >Precedent</a>
                </li>

                  {% endif %}

                  <li class="page-item active"> 
                      <a class="page-link" href="?page={{ liste.number }}">{{ liste.number }}</a>
                  </li>
                      


                  {% if liste.has_next %}
                  
                  
                  <li class="page-item ">
                    <a class="page-link" href="?page={{ liste.next_page_number }}">Suivant</a>
                  </li>

                    {% endif %}


              </ul>
       
      </div>

   </div>




	 </div>
	</div><!--End Row-->

  






























{% endblock content %}