admin/admin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from administrer import views
import authentication.views





urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include(('administrer.urls', 'adminstrer'), namespace='administrer')),
    path('index/', views.index, name='index'),
    path('inbox/notifications/',include(('notifications.urls', 'notifications'), namespace='notifications')),

    
    
    path('', authentication.views.login_page, name='login'),
    path('logout/', authentication.views.logout_user, name='logout'),
    path('signup/', authentication.views.signup_page, name='signup'),


    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin/administrer/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns =[

    path('index/', views.index, name='index'),
    path('statistique/', views.dashboard, name='dashboard'),

    path('add/personne', views.personne, name='person_add'),
    path('ajax/load-cities/', views.load_cities,name='ajax_load_cities'),  
    path('liste/personne', views.listePerson, name='person_changelist'),
    path('search/', views.search,name='search'),
    path('<int:id>/', views.ModiPers, name='person_change'),
    path('Supprimer/<int:id>', views.supPerson, name='supPerson'),
    path('details/<pk>', views.detail, name='details'),
    path('add/courrier', views.AddCour, name='AddCour'),
    path('liste/courrier', views.liste, name='liste'),
    path('modifier/courrier/<int:id>', views.Modif, name='Modif'),
    path('supprimer/courrier/<int:id>', views.suppression, name='suppression'),
    path('pdf/courrier/<pk>', views.pdf, name='pdf'),
    # path('statistique/courrier', views.listeDirec, name='listeDirec'),
    path('statistique/personnel', views.dash, name='dash'),














]
if settings.DEBUG:  # add this
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

admin/administrer/models.py
from unicodedata import name
from django.db import models

# Create your models here.




class Type_Service(models.Model):
    lib_TypeServ = models.CharField(
        verbose_name='type de service', max_length=50)

    def __str__(self):
        return (self.lib_TypeServ)


class Entite(models.Model):

    SERVICE = (
        ('Choix du Service', (
            ('Interne', 'Interne'),
            ('Externe', 'Externe'),
        ))),

    PERSONNE = (
        ('Choix du Type de Personne', (
            ('Morale', 'Morale'),
            ('Physique', 'Physique'),
        ))),

    nom_Entite = models.CharField(
        verbose_name="destinataire ou expediteur", max_length=50)
    service = models.CharField(max_length=50, choices=SERVICE)
    personne = models.CharField(max_length=50, choices=PERSONNE)
    date_creat = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (self.nom_Entite)


  


class Courrier(models.Model):
    CATEGORIE = (
        ('Choix de Type de Courrier', (
            ('TRANSMISSION', 'TRANSMISSION'),
            ('INTERNE', 'INTERNE'),
            ('ENTRANT', 'ENTRANT'),
            ('SORTANT', 'SORTANT'),
        ))),

    SEXE = (
        ('Choix du Sexe', (
            ('Feminin', 'feminin'),
            ('Masculin', 'masculin'),
        ))),

    num_ordre_cour = models.IntegerField(
        verbose_name="numero d ordre",unique=True,null=True)
    date_Emiss_cour = models.DateField('date Emission', null=True, blank=True)
    date_AccuseRecp_cour = models.DateField(
        'date de reception', null=True, blank=True)
    obj_cour = models.TextField()
    type_cour = models.CharField(max_length=20, null=True, choices=CATEGORIE)
    num_AccRecp_cour = models.PositiveIntegerField(
        verbose_name="numero accusé de reception", null=True, blank=True)
    file_cour = models.FileField(
        verbose_name="fichier", upload_to='static/upload', null=True)
    DestRecp = models.ForeignKey(
        Entite, verbose_name="destinataire ou recepteur", on_delete=models.CASCADE, null=True, related_name="DestRecp")
    date_ajout = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['date_ajout']

    class Meta:
        permissions = [("view_courrier_dashboard", "peut etre vu uniquement par le tableau de bords")]

    def __str__(self):
        return (self.type_cour)


class Arme(models.Model):
    lib_arm = models.CharField(max_length=150, verbose_name="nom d'Arme")

    def __str__(self):
        return (self.lib_arm)


class direction(models.Model):
    lib_dir = models.CharField(
        max_length=150, verbose_name="nom de la direction")

    def __str__(self):
        return (self.lib_dir)


class Diplome(models.Model):
    lib_dip = models.CharField(max_length=150)

    def __str__(self):
        return (self.lib_dip)


class Grade(models.Model):
    lib_grad = models.CharField(max_length=150, verbose_name="Grade")

    def __str__(self):
        return (self.lib_grad)


class sousDirection(models.Model):
    name = models.CharField(max_length=150, verbose_name="Nom de sous direction")
    direction = models.ForeignKey(direction, on_delete=models.CASCADE)

    def __str__(self):
        return (self.name)


class Service(models.Model):
    name = models.CharField(max_length=150, null=True)
    sousdirection = models.ForeignKey(
        sousDirection, on_delete=models.CASCADE, null=True)


    def __str__(self):
        return (self.name)





class Instruction(models.Model):
    intruc = models.CharField(max_length=150, null=True)

    def __str__(self):
        return (self.intruc)


class FicheAnalyse(models.Model):
    Observation=models.CharField(max_length=250,null=True)
    courrier=models.ForeignKey(Courrier,on_delete=models.CASCADE,null=True,related_name="Courrier")
    instru=models.ManyToManyField(Instruction)
    # service = models.ForeignKey(Service,on_delete=models.CASCADE)
    service = models.ManyToManyField(Service)

    def __str__(self):
        return (self.Observation)

















class Person(models.Model):

    SEXE = (
        ('Choix du sexe---', (
            ('Feminin', 'Feminin'),
            ('Masculin', 'masculin'),
        ))),

    TYPE = (
        ('Choisir type personne', (
            ('Civil', 'Civil'),
            ('Corps_habillé', 'Corps_habillé'),
        ))),

    SITUATION = (
        ('Choix du situation matrimoniale', (
            ('Marié', 'Marié(e)'),
            ('celibataire', 'Célibataire'),
        ))),

    nom_per = models.CharField(max_length=150, verbose_name='nom')
    pren_per = models.CharField(max_length=150, verbose_name='prenom')
    photo = models.ImageField(upload_to='static/images', verbose_name="photo",null=True)
    dteNaiss_per = models.DateField(verbose_name="date de naissance")
    lieu = models.CharField(max_length=200, null=True,
                            verbose_name="lieu de naissance")
    Mat_per = models.CharField(
        max_length=150, verbose_name="matricule", blank=True)
    Sex_per = models.CharField(
        max_length=150, null=True, choices=SEXE, verbose_name="sexe")
    post_per = models.CharField(
        max_length=150, verbose_name="FONCTION/OCCUPATION")
    Emai_per = models.EmailField(max_length=254, verbose_name="Email")
    tel_per = models.CharField(max_length=100, verbose_name="Telephone")
    numDec = models.CharField(
        verbose_name="numero de decision", max_length=100, blank=True, null=True)
    dom_per = models.CharField(max_length=150, verbose_name="domicile")
    deco_per = models.CharField(
        max_length=150, null=True, blank=True, verbose_name="decoration")
    Meca_per = models.CharField(
        max_length=150, blank=True, verbose_name="Mecano", null=True)
    stage_per = models.CharField(
        max_length=150, verbose_name="stage effectué", blank=True, null=True)
    Type_per = models.CharField(
        max_length=150, null=True, choices=TYPE, verbose_name="type de personne")
    numAr_per = models.IntegerField(
        blank=True, null=True, verbose_name="numéro d'arme")
    Arme = models.ForeignKey(Arme, on_delete=models.CASCADE, verbose_name="Arme", null=True,blank=True)
    Grades = models.ForeignKey(Grade, on_delete=models.CASCADE,null=True,blank=True, verbose_name="Grades")
    Diplomes = models.ManyToManyField(Diplome,related_name="Diplomes")
    formations = models.CharField(
        max_length=200, null=True, blank=True, verbose_name="formations")
    situa_pers = models.CharField(
        max_length=100, choices=SITUATION, verbose_name="situation matrimoniale")
    person = models.CharField(
        max_length=200, null=True, verbose_name="personne à contacter")
    datePrise = models.DateField(
        null=True, verbose_name="date prise de service")
    dateEnr = models.DateTimeField(
        auto_now=True, verbose_name="date d enregistrement")
    dateE = models.DateField(blank=True, null=True,
                             verbose_name="date d'entree à la police")
    AnSer_per = models.CharField(
        blank=True, null=True, verbose_name="TROIS DERNIERS SERVICE ET POSTE OCCUPES AVANT LA DITT", max_length=300)
    sousdirection = models.ForeignKey(sousDirection,models.SET_NULL,null=True)
    service = models.ForeignKey(Service,models.SET_NULL, verbose_name="service",null=True)

    class Meta:
        ordering = ['dateE']
        permissions = [("view_person_dashboard","peut etre vu uniquement par le tableau de bords")]
       

    def __str__(self):
        return (self.nom_per)

    def __str__(self):
        return (self.pren_per)

    def __str__(self):
        return (self.Mat_per)
    
    def __str__(self):
        return (self.deco_per)
    
    def __str__(self):
        return (self.post_per)

    def __str__(self):
        return (self.numDec)

    def __str__(self):
        return (self.dom_per)

    def __str__(self):
        return (self.Meca_per)

    def __str__(self):
        return (self.stage_per)

    def __str__(self):
        return (self.Type_per)

    def __str__(self):
        return (self.lieu)

    def __str__(self):
        return (self.formations)

    def __str__(self):
        return (self.person)

admin/administrer/forms.py
from django import forms
from .models import *
from django.forms import ModelForm


class XYZ_DateInput(forms.DateInput):
    input_type = "date"

    def __init__(self, **kwargs):
        kwargs["format"] = "%Y-%m-%d"
        # kwargs["format"] = "%d-%m-%Y"
        super().__init__(**kwargs)


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = "__all__"

        widgets = {
            'datePrise': XYZ_DateInput(format=["%Y-%m-%d"],),
            'dateEnr': XYZ_DateInput(format=["%Y-%m-%d"],),
            'dateE': XYZ_DateInput(format=["%Y-%m-%d"],),

            'dteNaiss_per': XYZ_DateInput(format=["%Y-%m-%d"],),
            'nom_per':forms.TextInput(attrs={'required': True}),

        }
      

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['service'].queryset = Service.objects.none()

        if 'sousdirection' in self.data:
            try:
                sousdirection_id = int(self.data.get('sousdirection'))
                self.fields['service'].queryset = Service.objects.filter(
                    sousdirection_id=sousdirection_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['service'].queryset = self.instance.sousdirection.service_set.order_by('name')


    
class EntiteForm(ModelForm):
    class Meta:
        model = Entite
        fields = "__all__"




class CourrierForm(ModelForm):
    class Meta:
        model = Courrier
        fields = "__all__"
        widgets = {
            'DestRecp': forms.Select(attrs={'class': 'form-control'}),
            'num_AccRecp_cour': forms.NumberInput(attrs={'class': 'form-control'}),
            'type_cour': forms.TextInput(attrs={'class': 'form-control'}),
            'obj_cour': forms.Textarea(attrs={'class': 'form-control',"rows":3, "cols":10}),
            'num_ordre_cour': forms.NumberInput(attrs={'class': 'form-control'}),
            'type_cour': forms.Select(attrs={'class': 'form-control','type': 'select'}),
            
            'date_Emiss_cour':XYZ_DateInput(format=["%Y-%m-%d"],),
            'date_AccuseRecp_cour': XYZ_DateInput(format=["%Y-%m-%d"],),
            
        }
   

admin/administrer/templates/base.html
{% load static %}
{% load notifications_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <meta name="description" content=""/>
  <meta name="author" content=""/>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <title>Application de la DITT</title>
  <!-- loader-->
  {% comment %} <link href="{% static 'assets/css/pace.min.css' %}" rel="stylesheet"/> {% endcomment %}
  <script src="{% static 'assets/js/pace.min.js' %}"></script>
  <!--favicon-->
  <link rel="icon" href="{% static 'assets/images/favicon.ico' %}" type="image/x-icon">
  <!-- Vector CSS -->
  <link href="{% static 'assets/plugins/vectormap/jquery-jvectormap-2.0.2.css' %}" rel="stylesheet"/>
  <!-- simplebar CSS-->
  <link href="{% static 'assets/plugins/simplebar/css/simplebar.css' %}" rel="stylesheet"/>
  <!-- Bootstrap core CSS-->
  <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet"/>
  <!-- animate CSS-->
  <link href="{% static 'assets/css/animate.css' %}" rel="stylesheet" type="text/css"/>
  <!-- Icons CSS-->
  <link href="{% static 'assets/css/icons.css' %}" rel="stylesheet" type="text/css"/>
  <!-- Sidebar CSS-->
  <link href="{% static 'assets/css/sidebar-menu.css' %}" rel="stylesheet"/>
  <!-- Custom Style-->
  <link href="{% static 'assets/css/app-style.css' %}" rel="stylesheet"/>
  
 <script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
 {% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}

  
</head>

<body class="bg-theme bg-theme3">
 
<!-- Start wrapper-->
 <div id="wrapper">
 
  <!--Start sidebar-wrapper-->
   <div id="sidebar-wrapper" data-simplebar="" data-simplebar-auto-hide="true">
     <div class="brand-logo">
      <a href="#">
       <img src="{% static 'assets/images/DITT.png' %}" class="logo-icon" alt="logo icon">
       <h5 class="logo-text">administrer</h5>
     </a>
   </div>
   <ul class="sidebar-menu do-nicescrol">
    <li>
     
    </li> 
    {% if perms.administrer.view_personne_dashboard %}

      <li class="sidebar-header">GESTION DU PERSONNEL</li>
      
     <li>
        <a href="{% url 'administrer:dash' %}">
          <i class="zmdi zmdi-invert-colors"></i> <span>Tableau de Bords</span>
        </a>
        {% endif %}

      </li> 

    {% if perms.administrer.add_person %}

       <li>
        <a href="{% url 'administrer:person_add' %}">
          <i class="zmdi zmdi-format-list-bulleted"></i> <span>Formulaire</span>
                    <small class="badge float-right badge-light">Nouveau</small>
        </a>
      </li>

    {% endif %}



      <li>
        {% if perms.administrer.view_person %}
        <a href="{% url 'administrer:person_changelist' %}">
          <i class="zmdi zmdi-grid"></i> <span>Liste</span>
        </a>
        {% endif %}

      </li>
      {% if perms.administrer.view_courrier_dashboard %}

      <li class="sidebar-header">GESTION DU COURRIER</li>
      <li>
        <a href="{% url 'administrer:dashboard' %}">
          <i class="zmdi zmdi-view-dashboard"></i> <span>Tableau de Bords</span>
        </a>
      </li>
    {% endif %}


    {% if perms.administrer.add_courrier %}
      <li>
        <a href="{% url 'administrer:AddCour' %}">
          <i class="zmdi zmdi-format-list-bulleted"></i> <span>Formulaire</span>
                    <small class="badge float-right badge-light">Nouveau</small>
        </a>
      </li>
    {% endif %}



  {% if perms.administrer.view_courrier %}

      <li>
        <a href="{% url 'administrer:liste' %}">
          <i class="zmdi zmdi-grid"></i> <span>Liste</span>
        </a>
      </li>
      {% endif %}


{% comment %} 

      <li class="sidebar-header">GESTION DE LA FICHE ANALYSE</li>
      <li>
        <a href="#">
          <i class="zmdi zmdi-view-dashboard"></i> <span>Dashboard</span>
        </a>
      </li>
      <li>
        <a href="{% url 'administrer:listeDirec' %}">
          <i class="zmdi zmdi-grid"></i> <span>Liste</span>
        </a>
      </li>

      <li>
        <a href="#">
          <i class="zmdi zmdi-grid"></i> <span>FICHE ANALYSE TRAITEE</span>
        </a>
      </li> {% endcomment %}

    </ul>
   
   </div>
   <!--End sidebar-wrapper-->

<!--Start topbar header-->
<header class="topbar-nav">
  <nav class="navbar navbar-expand fixed-top">
   <ul class="navbar-nav mr-auto align-items-center">
     <li class="nav-item">
       <a class="nav-link toggle-menu" href="javascript:void();">
        <i class="icon-menu menu-icon"></i>
      </a>
      </li>
      <li class="nav-item">
     
     </li>
    </ul>
      
    <ul class="navbar-nav align-items-center right-nav-link">
     <li class="nav-item dropdown-lg">
       <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown" href="javascript:void();">
       <i class="fa fa-envelope-open-o"></i></a>
       </li>
   
         <li class="nav-item dropdown">
                 <a href="#" class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown" >
                           <i class="fa fa-bell-o"></i> <span class="badge-notifications badge badge-pill badge-danger" style="float:right;margin-bottom:-3px;margin-top: -2px !important; margin-left:20px !important; font-size: 0.6rem;">
         {% live_notify_badge %}
           </span> 
                     <span class="glyphicon glyphicon-user pull-right">
 
                     </span>
                 </a>
                 <ul class="dropdown-menu" id="notice-link">
                   <a href="{% url 'notifications:unread' %}">
          {% live_notify_list %}
                   </a>
                 </ul>
             </li>
 
 
     </a>
     <ul class="dropdown-menu dropdown-menu-right">
        <li class="dropdown-item user-details">
         <a href="javaScript:void();">
           
            <div class="media">
              <div class="avatar"></div>
             <div class="media-body">
 
           <h6 class="mt-2 user-title">r</h6>
             <p class="user-subtitle">z</p>
             </div>
            </div>
           </a>
         </li>
         <li class="dropdown-divider"></li>
         <li class="dropdown-divider"></li>
         <li class="dropdown-item">
          </a>
         </li>
         <li class="dropdown-divider"></li>
       </ul>
 
 
     </li>
 
     <li class="nav-item">
       <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" data-toggle="dropdown" href="#">
         <span class="user-profile"><img src="https://via.placeholder.com/110x110" class="img-circle" alt="user avatar"></span>
       </a>
       
       <ul class="dropdown-menu dropdown-menu-right">
        <li class="dropdown-item user-details">
         <a href="javaScript:void();">
           
            <div class="media">
              <div class="avatar"><img class="align-self-start mr-3" src="https://via.placeholder.com/110x110" alt="user avatar"></div>
             <div class="media-body">
 
             {%  if user.is_authenticated %}
 
           <h6 class="mt-2 user-title">{{ request.user }}</h6>
             <p class="user-subtitle">{{ request.email }}</p>
             </div>
            </div>
           </a>
         </li>
         <li class="dropdown-divider"></li>
         {% comment %} <li class="dropdown-item"><i class="icon-envelope mr-2"></i> Inbox</li> {% endcomment %}
         <li class="dropdown-divider"></li>
         {% comment %} <li class="dropdown-item"><i class="icon-wallet mr-2"></i> Account</li> {% endcomment %}
         <li class="dropdown-item">
           <a href="{% url 'admin:index' %}">
           <i class="icon-settings mr-2"></i>Setting
          </a>
         </li>
         <li class="dropdown-divider"></li>
 
 
           <li class="dropdown-item"><i class="icon-power mr-2"></i> <a href="{% url 'logout' %}">Logout</a></li>
    
       {% endif %}
 
       </ul>
     </li>
   </ul>
 </nav>
 </header>
    
<!--End topbar header-->

<div class="clearfix"></div>
	
  <div class="content-wrapper">
    <div class="container-fluid">

 

      {% block content %} {% endblock %}

	
  <!--start color switcher-->
   <div class="right-sidebar">
    <div class="switcher-icon">
      <i class="zmdi zmdi-settings zmdi-hc-spin"></i>
    </div>
    <div class="right-sidebar-content">

      <p class="mb-0">Gaussion Texture</p>
      <hr>
      
      <ul class="switcher">
        <li id="theme1"></li>
        <li id="theme2"></li>
        <li id="theme3"></li>
        <li id="theme4"></li>
        <li id="theme5"></li>
        <li id="theme6"></li>
      </ul>

      <p class="mb-0">Gradient Background</p>
      <hr>
      
      <ul class="switcher">
        <li id="theme7"></li>
        <li id="theme8"></li>
        <li id="theme9"></li>
        <li id="theme10"></li>
        <li id="theme11"></li>
        <li id="theme12"></li>
		    <li id="theme13"></li>
        <li id="theme14"></li>
        <li id="theme15"></li>
      </ul>
      
     </div>
   </div>
  <!--end color switcher-->
   
  </div><!--End wrapper-->


  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'assets/js/jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
	
	
 <!-- simplebar js -->
 <script src="{% static 'assets/plugins/simplebar/js/simplebar.js' %}"></script>
 <!-- sidebar-menu js -->
 <script src="{% static 'assets/js/sidebar-menu.js' %}"></script>
 <!-- loader scripts -->
  <script src="{% static 'assets/js/jquery.loading-indicator.js' %}"></script>
  <!-- Custom scripts -->
  <script src="{% static 'assets/js/app-script.js' %}"></script>
  <!-- Chart js -->
  
  <script src="{% static 'assets/plugins/Chart.js/Chart.min.js' %}"></script>
 
  <!-- Index js -->
  <script src="{% static 'assets/js/index.js' %}"></script>
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

  
   <!-- Option 1: Bootstrap Bundle with Popper -->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  

  <script>
    {% for msg in messages %}
     swal('{{ msg }}');
   {% endfor %}
  </script>



<script>

  function delete_user(selected_user){
    document.getElementById("item-delete-form").action = selected_user.href
}

</script>



<script>

  function my_special_notification_callback(data) { 
    for (var i=0; i < data.unread_list.length; i++) { 
        msg = data.unread_list[i]; 
        console.log(msg); 
    } 
}

</script>


</body>
</html>

admin/administrer/templates/index.html
 {% extends 'base.html' %} 

admin/administrer/templates/{% extends 'base.html' %}.html
from django.db import migrations


def create_groups(apps, schema_migration):
    User = apps.get_model('authentication', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_courrier = Permission.objects.get(codename='add_courrier')
    change_courrier = Permission.objects.get(codename='change_courrier')
    delete_courrier = Permission.objects.get(codename='delete_courrier')
    view_courrier = Permission.objects.get(codename='view_courrier')
    add_entite = Permission.objects.get(codename='add_entite')
    change_entite = Permission.objects.get(codename='change_entite')
    delete_entite = Permission.objects.get(codename='delete_entite')
    view_entite = Permission.objects.get(codename='view_entite')
    view_courrier_dashboard = Permission.objects.get(codename='view_courrier_dashboard')
    add_personne = Permission.objects.get(codename='add_personne')

    change_personne = Permission.objects.get(codename='change_personne')
    delete_personne = Permission.objects.get(codename='delete_personne')
    view_personne = Permission.objects.get(codename='view_personne')
    add_demande = Permission.objects.get(codename='add_demande')

    add_demande = Permission.objects.get(codename='add_demande')
    view_demande = Permission.objects.get(codename='view_demande')
    view_demande_chef = Permission.objects.get(codename='view_demande_chef')


    view_personne_dashboard = Permission.objects.get(codename='view_personne_dashboard')

   

    administration_permissions = [
        add_personne,
        change_personne,
        view_personne,
        delete_personne,
        add_courrier,
        change_courrier,
        delete_courrier,
        view_courrier,
        add_entite,
        change_entite,
        delete_entite,
        view_entite,
        view_courrier_dashboard,
        add_personne,
        add_demande,
        view_courrier_dashboard,
        view_personne_dashboard,
        view_demande,
    ]

    personnel_permissions = [
        add_personne,
        add_demande,
    ]

    secretariat_permissions = [
        add_courrier,
        change_courrier,
        delete_courrier,
        view_courrier,
        add_entite,
        change_entite,
        delete_entite,
        view_entite,
        view_courrier_dashboard,
        add_demande,
        view_courrier_dashboard,
        view_demande,
    ]

    secretariat = Group(name='secretariat')
    secretariat.save()
    secretariat.permissions.set(secretariat_permissions)

    personnel = Group(name='personnel')
    personnel.save()
    personnel.permissions.set(personnel_permissions)

    administration = Group(name='administration')
    administration.save()
    administration.permissions.set(administration_permissions)

 

    for user in User.objects.all():
       if user.role == 'SECRETARIAT':
          secretariat.user_set.add(user)
       if user.role == 'PERSONNEL':
          personnel.user.set.add(user)
       if user.role == 'ADMINISTRATION':
          administration.user.set.add(user)
     

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),


    ]

    operations = [

        migrations.RunPython(create_groups)

    ]