admin/admin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from administrer import views
import authentication.views





urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include(('administrer.urls', 'adminstrer'), namespace='administrer')),
    path('index/', views.index, name='index'),
    path('inbox/notifications/',include(('notifications.urls', 'notifications'), namespace='notifications')),

    
    
    path('', authentication.views.login_page, name='login'),
    path('logout/', authentication.views.logout_user, name='logout'),
    path('signup/', authentication.views.signup_page, name='signup'),


    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin/administrer/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns =[

    path('index/', views.index, name='index'),
    path('statistique/', views.dashboard, name='dashboard'),

    path('add/personne', views.personne, name='person_add'),
    path('ajax/load-cities/', views.load_cities,name='ajax_load_cities'),  
    path('liste/personne', views.listePerson, name='person_changelist'),
    path('search/', views.search,name='search'),
    path('<int:id>/', views.ModiPers, name='person_change'),
    path('Supprimer/<int:id>', views.supPerson, name='supPerson'),
    path('details/<pk>', views.detail, name='details'),
    path('add/courrier', views.AddCour, name='AddCour'),
    path('liste/courrier', views.liste, name='liste'),
    path('modifier/courrier/<int:id>', views.Modif, name='Modif'),
    path('supprimer/courrier/<int:id>', views.suppression, name='suppression'),
    path('pdf/courrier/<pk>', views.pdf, name='pdf'),
    # path('statistique/courrier', views.listeDirec, name='listeDirec'),
    path('statistique/personnel', views.dash, name='dash'),














]
if settings.DEBUG:  # add this
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

admin/administrer/models.py
from unicodedata import name
from django.db import models

# Create your models here.




class Type_Service(models.Model):
    lib_TypeServ = models.CharField(
        verbose_name='type de service', max_length=50)

    def __str__(self):
        return (self.lib_TypeServ)


class Entite(models.Model):

    SERVICE = (
        ('Choix du Service', (
            ('Interne', 'Interne'),
            ('Externe', 'Externe'),
        ))),

    PERSONNE = (
        ('Choix du Type de Personne', (
            ('Morale', 'Morale'),
            ('Physique', 'Physique'),
        ))),

    nom_Entite = models.CharField(
        verbose_name="destinataire ou expediteur", max_length=50)
    service = models.CharField(max_length=50, choices=SERVICE)
    personne = models.CharField(max_length=50, choices=PERSONNE)
    date_creat = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (self.nom_Entite)


  


class Courrier(models.Model):
    CATEGORIE = (
        ('Choix de Type de Courrier', (
            ('TRANSMISSION', 'TRANSMISSION'),
            ('INTERNE', 'INTERNE'),
            ('ENTRANT', 'ENTRANT'),
            ('SORTANT', 'SORTANT'),
        ))),

    SEXE = (
        ('Choix du Sexe', (
            ('Feminin', 'feminin'),
            ('Masculin', 'masculin'),
        ))),

    num_ordre_cour = models.IntegerField(
        verbose_name="numero d ordre",unique=True,null=True)
    date_Emiss_cour = models.DateField('date Emission', null=True, blank=True)
    date_AccuseRecp_cour = models.DateField(
        'date de reception', null=True, blank=True)
    obj_cour = models.TextField()
    type_cour = models.CharField(max_length=20, null=True, choices=CATEGORIE)
    num_AccRecp_cour = models.PositiveIntegerField(
        verbose_name="numero accusé de reception", null=True, blank=True)
    file_cour = models.FileField(
        verbose_name="fichier", upload_to='static/upload', null=True)
    DestRecp = models.ForeignKey(
        Entite, verbose_name="destinataire ou recepteur", on_delete=models.CASCADE, null=True, related_name="DestRecp")
    date_ajout = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['date_ajout']

    class Meta:
        permissions = [("view_courrier_dashboard", "peut etre vu uniquement par le tableau de bords")]

    def __str__(self):
        return (self.type_cour)


class Arme(models.Model):
    lib_arm = models.CharField(max_length=150, verbose_name="nom d'Arme")

    def __str__(self):
        return (self.lib_arm)


class direction(models.Model):
    lib_dir = models.CharField(
        max_length=150, verbose_name="nom de la direction")

    def __str__(self):
        return (self.lib_dir)


class Diplome(models.Model):
    lib_dip = models.CharField(max_length=150)

    def __str__(self):
        return (self.lib_dip)


class Grade(models.Model):
    lib_grad = models.CharField(max_length=150, verbose_name="Grade")

    def __str__(self):
        return (self.lib_grad)


class sousDirection(models.Model):
    name = models.CharField(max_length=150, verbose_name="Nom de sous direction")
    direction = models.ForeignKey(direction, on_delete=models.CASCADE)

    def __str__(self):
        return (self.name)


class Service(models.Model):
    name = models.CharField(max_length=150, null=True)
    sousdirection = models.ForeignKey(
        sousDirection, on_delete=models.CASCADE, null=True)


    def __str__(self):
        return (self.name)





class Instruction(models.Model):
    intruc = models.CharField(max_length=150, null=True)

    def __str__(self):
        return (self.intruc)


class FicheAnalyse(models.Model):
    Observation=models.CharField(max_length=250,null=True)
    courrier=models.ForeignKey(Courrier,on_delete=models.CASCADE,null=True,related_name="Courrier")
    instru=models.ManyToManyField(Instruction)
    # service = models.ForeignKey(Service,on_delete=models.CASCADE)
    service = models.ManyToManyField(Service)

    def __str__(self):
        return (self.Observation)

















class Person(models.Model):

    SEXE = (
        ('Choix du sexe---', (
            ('Feminin', 'Feminin'),
            ('Masculin', 'masculin'),
        ))),

    TYPE = (
        ('Choisir type personne', (
            ('Civil', 'Civil'),
            ('Corps_habillé', 'Corps_habillé'),
        ))),

    SITUATION = (
        ('Choix du situation matrimoniale', (
            ('Marié', 'Marié(e)'),
            ('celibataire', 'Célibataire'),
        ))),

    nom_per = models.CharField(max_length=150, verbose_name='nom')
    pren_per = models.CharField(max_length=150, verbose_name='prenom')
    photo = models.ImageField(upload_to='static/images', verbose_name="photo",null=True)
    dteNaiss_per = models.DateField(verbose_name="date de naissance")
    lieu = models.CharField(max_length=200, null=True,
                            verbose_name="lieu de naissance")
    Mat_per = models.CharField(
        max_length=150, verbose_name="matricule", blank=True)
    Sex_per = models.CharField(
        max_length=150, null=True, choices=SEXE, verbose_name="sexe")
    post_per = models.CharField(
        max_length=150, verbose_name="FONCTION/OCCUPATION")
    Emai_per = models.EmailField(max_length=254, verbose_name="Email")
    tel_per = models.CharField(max_length=100, verbose_name="Telephone")
    numDec = models.CharField(
        verbose_name="numero de decision", max_length=100, blank=True, null=True)
    dom_per = models.CharField(max_length=150, verbose_name="domicile")
    deco_per = models.CharField(
        max_length=150, null=True, blank=True, verbose_name="decoration")
    Meca_per = models.CharField(
        max_length=150, blank=True, verbose_name="Mecano", null=True)
    stage_per = models.CharField(
        max_length=150, verbose_name="stage effectué", blank=True, null=True)
    Type_per = models.CharField(
        max_length=150, null=True, choices=TYPE, verbose_name="type de personne")
    numAr_per = models.IntegerField(
        blank=True, null=True, verbose_name="numéro d'arme")
    Arme = models.ForeignKey(Arme, on_delete=models.CASCADE, verbose_name="Arme", null=True,blank=True)
    Grades = models.ForeignKey(Grade, on_delete=models.CASCADE,null=True,blank=True, verbose_name="Grades")
    Diplomes = models.ManyToManyField(Diplome,related_name="Diplomes")
    formations = models.CharField(
        max_length=200, null=True, blank=True, verbose_name="formations")
    situa_pers = models.CharField(
        max_length=100, choices=SITUATION, verbose_name="situation matrimoniale")
    person = models.CharField(
        max_length=200, null=True, verbose_name="personne à contacter")
    datePrise = models.DateField(
        null=True, verbose_name="date prise de service")
    dateEnr = models.DateTimeField(
        auto_now=True, verbose_name="date d enregistrement")
    dateE = models.DateField(blank=True, null=True,
                             verbose_name="date d'entree à la police")
    AnSer_per = models.CharField(
        blank=True, null=True, verbose_name="TROIS DERNIERS SERVICE ET POSTE OCCUPES AVANT LA DITT", max_length=300)
    sousdirection = models.ForeignKey(sousDirection,models.SET_NULL,null=True)
    service = models.ForeignKey(Service,models.SET_NULL, verbose_name="service",null=True)

    class Meta:
        ordering = ['dateE']
        permissions = [("view_person_dashboard","peut etre vu uniquement par le tableau de bords")]
       

    def __str__(self):
        return (self.nom_per)

    def __str__(self):
        return (self.pren_per)

    def __str__(self):
        return (self.Mat_per)
    
    def __str__(self):
        return (self.deco_per)
    
    def __str__(self):
        return (self.post_per)

    def __str__(self):
        return (self.numDec)

    def __str__(self):
        return (self.dom_per)

    def __str__(self):
        return (self.Meca_per)

    def __str__(self):
        return (self.stage_per)

    def __str__(self):
        return (self.Type_per)

    def __str__(self):
        return (self.lieu)

    def __str__(self):
        return (self.formations)

    def __str__(self):
        return (self.person)

admin/administrer/forms.py
from django import forms
from .models import *
from django.forms import ModelForm


class XYZ_DateInput(forms.DateInput):
    input_type = "date"

    def __init__(self, **kwargs):
        kwargs["format"] = "%Y-%m-%d"
        # kwargs["format"] = "%d-%m-%Y"
        super().__init__(**kwargs)


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = "__all__"

        widgets = {
            'datePrise': XYZ_DateInput(format=["%Y-%m-%d"],),
            'dateEnr': XYZ_DateInput(format=["%Y-%m-%d"],),
            'dateE': XYZ_DateInput(format=["%Y-%m-%d"],),

            'dteNaiss_per': XYZ_DateInput(format=["%Y-%m-%d"],),
            'nom_per':forms.TextInput(attrs={'required': True}),

        }
      

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['service'].queryset = Service.objects.none()

        if 'sousdirection' in self.data:
            try:
                sousdirection_id = int(self.data.get('sousdirection'))
                self.fields['service'].queryset = Service.objects.filter(
                    sousdirection_id=sousdirection_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['service'].queryset = self.instance.sousdirection.service_set.order_by('name')


    
class EntiteForm(ModelForm):
    class Meta:
        model = Entite
        fields = "__all__"




class CourrierForm(ModelForm):
    class Meta:
        model = Courrier
        fields = "__all__"
        widgets = {
            'DestRecp': forms.Select(attrs={'class': 'form-control'}),
            'num_AccRecp_cour': forms.NumberInput(attrs={'class': 'form-control'}),
            'type_cour': forms.TextInput(attrs={'class': 'form-control'}),
            'obj_cour': forms.Textarea(attrs={'class': 'form-control',"rows":3, "cols":10}),
            'num_ordre_cour': forms.NumberInput(attrs={'class': 'form-control'}),
            'type_cour': forms.Select(attrs={'class': 'form-control','type': 'select'}),
            
            'date_Emiss_cour':XYZ_DateInput(format=["%Y-%m-%d"],),
            'date_AccuseRecp_cour': XYZ_DateInput(format=["%Y-%m-%d"],),
            
        }
   

admin/administrer/templates/personnel/liste.html
<option value="">---------</option>
{% for service in services %}
<option value="{{ service.pk }}">{{ service.name }}</option>
{% endfor %}

admin/administrer/templates/personnel/liste_per.html
{% extends 'base.html' %}

{% block content %}
 

<div class="clearfix"></div>

  <!--Start Dashboard Content-->

</br>
</br>
</br>


	
<div class="container">
{% include "personnel/search_form.html" %}

 {% if person|length_is:"0" %}
     </br>
      </br>
     <div class="text-center text-danger"> <p>Pas de Personnel!!!</div>

 {% else %}

  </div>

  </br>
  </br>
  </br>
	<div class="row">
	 <div class="col-12 col-lg-12">
	   <div class="card">
	     <div class="card-header"><a href="{% url 'administrer:person_add' %}" class="btn btn-icon btn-primary" ><i class="zmdi zmdi-account-add"></i></a>

	       <div class="table-responsive">
                 <table class="table  table table-hover align-items-center table-flush table-borderless">
                  <thead>
                   <tr>
                    <th scope="col">Photo</th>

                    <th scope="col">Date d'Enregistrment</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Prenom</th>
                    <th scope="col">Date Naissance</th>
                    <th scope="col">Matricule</th>
                    <th scope="col">Mecano</th>
                    <th scope="col">Type Personne</th>
                    <th scope="col">Service</th>
                    <th scope="col">Operations</th>
                   </tr>
                   </thead>
                   <tbody>
              {% for person in person  %}

                  <tr>
                    <td><a href="/media/{{person.photo}}">
                      <img src="{{ person.photo.url }}" class="product-img" alt="product img" width="30px">
                    <td>{{ person.dateEnr }}</td>
                    <td>{{ person.nom_per|upper }}</td>
                    <td>{{ person.pren_per }}</td>
                    <td>{{ person.dteNaiss_per }}</td>
                    <td>{{ person.Mat_per }}</td>
                    <td>{{ person.Meca_per }}</td>
                    <td style="font-weight:bold; font-size:1em;" class="container mt-2 fst-italic {% if  person.Type_per == "Civil" %}badge rounded-pill bg-warning{% else %}badge rounded-pill bg-success{% endif %}">{{ person.Type_per }}</td>
                    <td>{{ person.service }}</td>
                    
                    <td>
                      <a href="{% url 'administrer:person_change'  person.id %}" class="btn btn-icon btn-primary"><i class="fa fa-pencil"></i></a>
                      <a href="{% url 'administrer:details'  person.id %}" class="btn btn-icon btn-warning"><i class="fa fa-eye"></i></a>


                      <a
                href="{% url 'administrer:supPerson' person.id %}"
                class="btn btn-icon btn-danger "
                data-toggle="modal"
                data-target="#delete-item-modal"
                onclick="delete_user(this)">

                <i class="fa fa-trash"></i>

              </a>


            </td>

              <div class="modal fade" id="delete-item-modal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                          <p class="text-danger fw-bold">êtes-vous sûr de vouloir supprimer???</p>
                        </div>
                        <div class="justify-content-between mb-2 mr-2 text-right">
                            <form method="post"
                                  id="item-delete-form"
                            >
                                <button type="button" class="btn btn-secondary mr-1" data-dismiss="modal">Annuler</button>
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger" id="confirm-delete-item-button">Supprimer</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>


                    </td>
                    
                   </tr>

                   

				

                 </tbody>
        {% endfor %}
{% endif %}
                
                </table>
               </div>
	   </div>

    
    <div class="row mt-3">
      <div class="col-md-3 offset-md-4">

              <ul class="pagination">

                  {% if page_obj.has_previous %}
                  
                      
                  <li class="page-item ">
                    <a class="page-link" href="?page= {{ page_obj.previous_page_number }}" >Precedent</a>
                  </li>

                  {% endif %}

                  <li class="page-item active"> 
                      <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                  </li>
                      


                  {% if page_obj.has_next %}
                  
                  
                  <li class="page-item ">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Suivant</a>
                  </li>

                    {% endif %}


              </ul>
       
      </div>

    </div>  
	 </div>
	</div><!--End Row-->



{% endblock content %}
                    

admin/administrer/templates/personnel/notification.html
{% extends 'base.html' %}


<ul class="notifications">
  {% for notice in notifications %}
    {% include 'notifications/notice.html' %}
  {% endfor %}
</ul>

admin/administrer/templates/personnel/person_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
  
<br/>
<br/>
<br/>
<br/>

	
    <div class="section-body">
      <div class="row">
        <div class="col-12 col-md-6 col-lg-12">
          <div class="card border b+">
            <form method="POST" id="formonForm" enctype="multipart/form-data" class="form-sample" data-cities-url="{% url 'administrer:ajax_load_cities' %}" novalidate>
              <div class="card-header">

          <h5 class="card-title text-uppercase"><CENTER><h4> <i class="zmdi zmdi-account" aria-hidden="true">FORMULAIRE D'AJOUT DU PERSONNEL</i></h4></CENTER>
              </div>
              <div class="card-body">
                
  <div class="row">
    <div class="col">
      <div class="form-outline">

             <label class="form-label" for="form6Example2"
          >Nom(s):</label>
        <div class="input-group mb-3 w-100 mt-2 p-2 ">
        

        {{ form.nom_per|add_class:'form-control'}}
            <!-- Button trigger modal -->

       </div>
      <div style="color:red">{{ form.nom_per.errors }}</div>

      </div>
    </div>
    <div class="col">
      &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
       &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
      <div class="form-outline">
        <label class="form-label" for="form6Example2"
          >Prénom(s):</label
        >
        {{ form.pren_per|add_class:'form-control'}}
      </div>
      <div style="color:red">{{ form.pren_per.errors }}</div>


    </div>

      <div class="col">
         &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
       &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
        <div class="form-outline">
          <label class="form-label" for="form6Example1"
            >Date de Naissance :</label
          >
        {{ form.dteNaiss_per|add_class:'form-control'}}
        
     <div style="color:red">{{ form.dteNaiss_per.errors }}</div>



        </div>
      </div>

  <div class="col">
     &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
       &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
      <div class="form-outline">
        <label class="form-label" for="form6Example2"
          >photo:</label
        >

        {{ form.photo|add_class:'form-control'}}
   <div style="color:red">{{ form.photo.errors }}</div>


      </div>
    </div>

  </div>

  <div class="row mb-4">
    
      <div class="col">
        <div class="form-outline">
          <label class="form-label" for="form6Example2"
            >Lieu de Naissance:</label
          >
        {{ form.lieu|add_class:'form-control'}}
      <div style="color:red">{{ form.lieu.errors }}</div>
        </div>
      </div>

       <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example1"
          >Sexe:</label
        >
          {{ form.Sex_per|add_class:'form-control'}}
      </div>
  <div style="color:red">{{ form.Sex_per.errors }}</div>

    </div>

       <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example2"
          >Type de Personne:</label
        >
    {{ form.Type_per|add_class:'form-control'}}
      </div>
  <div style="color:red">{{ form.Type_per.errors }}</div>

    </div>



  <div class="col">
        <div class="form-outline">
          <label class="form-label" for="form6Example1"
            >Matricule:</label
          >
          {{ form.Mat_per|add_class:'form-control'}}

          {% comment %} {% render_field form.date_Emiss_cour|add_class:"form-control" type="date" placeholder="select" %} {% endcomment %}

        </div>
      </div>




    </div>

  <div class="row mb-4">
   


  <div class="col">
        <div class="form-outline">
          <label class="form-label" for="form6Example1"
            >Fonction/Occupation(s):</label
          >
          {{ form.post_per|add_class:'form-control'}}

          {% comment %} {% render_field form.date_Emiss_cour|add_class:"form-control" type="date" placeholder="select" %} {% endcomment %}

        </div>
        <div style="color:red">{{ form.post_per.errors }}</div>

      </div>

    <div class="col">
      <div class="form-outline">

<label class="form-label" for="form6Example1" 
          >Email:</label
        >
    {{ form.Emai_per|add_class:'form-control'}}
      </div>
      <div style="color:red">{{ form.Emai_per.errors }}</div>
    </div>
<div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example1"
          >Telephone(s):</label
        >
    {{ form.tel_per|add_class:'form-control'}}
      </div>
      <div style="color:red">{{ form.tel_per.errors }}</div>

    </div>

    <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example1"
          >Domicile:</label
        >

        {{ form.dom_per|add_class:'form-control'}}

      </div>
      <div style="color:red">{{ form.dom_per.errors }}</div>

    </div>



  </div>

 




  <div class="row mb-4">
    <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example1"
          >Mecano:</label
        >
    {{ form.Meca_per|add_class:'form-control'}}

      </div>
    </div>

     <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example1"
          >Numero de Décison:</label
        >
    {{ form.numDec|add_class:'form-control'}}


      </div>
    </div>



    <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example1"
          >Stage(s):</label
        >

        {{ form.stage_per|add_class:'form-control'}}

      </div>
      <div style="color:red">{{ form.stage_per.errors }}</div>

    </div>

    
    <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example2"
          >Décoration:</label
        >
    {{ form.deco_per|add_class:'form-control'}}

     
      </div>
    </div>


 
  </div>





  <div class="row mb-4">

          
   <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example1"
          >Situation Matrimoniale:</label
        >
    {{ form.situa_pers|add_class:'form-control'}}


      </div>
      <div style="color:red">{{ form.situa_pers.errors }}</div>


    </div>


    <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example1"
          >Numero d'Arme:</label
        >
    {{ form.numAr_per|add_class:'form-control'}}

      </div>
    </div>

    <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example1"
          >Type d'Arme:</label
        >

        {{ form.Arme|add_class:'form-control'}}

      </div>
    </div>

    <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example2"
          >Grade:</label
        >
    {{ form.Grades|add_class:'form-control'}}

     
      </div>
    </div>

  </div>
  <div class="row mb-4">
  
      <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example1"
          >Diplome(s):</label
        >
    {{ form.Diplomes|add_class:'form-control'}}


      </div>
          <div style="color:red">{{ form.Diplomes.errors }}</div>

    </div>

    <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example1"
          >Sous_Direction:</label
        >

        {{ form.sousdirection|add_class:'form-control'}}

      </div>
          <div style="color:red">{{ form.sousdirection.errors }}</div>

    </div>

    <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example2"
          >Service:</label
        >
    {{ form.service|add_class:'form-control'}}
      </div>
          <div style="color:red">{{ form.service.errors }}</div>

    </div>


      <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example1"
          >personne(s) à Contacter:</label
        >

        {{ form.person|add_class:'form-control'}}

      </div>
<div style="color:red">{{ form.person.errors }}</div>


    </div>
  </div>
  <div class="row mb-4">
    <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example2"
          >Date de Prise de service:</label
        >
    {{ form.datePrise|add_class:'form-control'}}
      </div>
          <div style="color:red">{{ form.datePrise.errors }}</div>

    </div>


      <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example2"
          >Formation(s):</label
        >
    {{ form.formations|add_class:'form-control'}}
      </div>

    </div>

           
    <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example1"
          >Date d'Entrée à la Police:</label
        >
    {{ form.dateE|add_class:'form-control'}}
      </div>
    
    </div>

    <div class="col">
      <div class="form-outline">
        <label class="form-label" for="form6Example2"
          >TROIS DERNIERS SERVICE ET POSTE OCCUPES AVANT LA DITT:</label
        >
    {{ form.AnSer_per|add_class:'form-control'}}

     
      </div>
    </div>
  </div>


  </div>

  {% csrf_token %}

              </div>
              <div class="card-footer text-center">
                  <button type="submit" class="btn btn-primary">
                    <i class="fa fa-magic"></i>&nbsp; Valider
                  </button>
             
              </div>
            </form>
            <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
            <script>
              $("#id_sousdirection").change(function () {
                var url = $("#formonForm").attr("data-cities-url");  // get the url of the `load_cities` view
                var sousdirectionId = $(this).val();  // get the selected country ID from the HTML input
          
                $.ajax({                       // initialize an AJAX request
                  url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                  data: {
                    'sousdirection': sousdirectionId      // add the country id to the GET parameters
                  },
                  success: function (data) {   // `data` is the return of the `load_cities` view function
                    $("#id_service").html(data);  // replace the contents of the city input with the data that came from the server
                  }
                });
          
              });
            </script> 
          
	<!--start overlay-->
		  <div class="overlay toggle-menu"></div>
		<!--end overlay-->

    </div>
    <!-- End container-fluid-->

    


   </div><!--End content-wrapper-->
   <!--Start Back To Top Button-->
    <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
    <!--End Back To Top Button-->
	
	<!--Start footer-->
	
  <!--end color switcher-->
   

 
  




{% endblock content %}